default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 17963898310
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: user_database-1

test:
  <<: *default
  database: user_database_02

production:
  <<: *default
  database: user_database_02
